version: "2"

services:
  web:
    build: .
    command: bash -c "npm start"
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    image: mongo:latest
    user: mongodb
    expose:
      - "27017"
